### PR TITLE
Fix for floordiv on GPU target

### PR DESCRIPTION
**Pull request by edopao**
This PR addresses a `floordiv` runtime error detected on GPU target: `std::ifloor` returns zero with integer argument (for example, the result of an `int` division).

This change was initially part of #1442. It has been moved to this PR to let #1442 focus on the CUDA-codegen issue.

### CODE REVIEW

**Review by tbennun — CHANGES_REQUESTED** [review]
This looks good overall. I think there should be a test for correctness but otherwise approved.

**Comment by edopao** [comment]
@tbennun Test added, I have also updated the return type of the `ifloor` template for integral argument type.

**Comment by edopao** [comment]
Auto-format on save, I will remove all white-space changes. Sorry for that.

**Comment by tbennun** [comment]
> Auto-format on save, I will remove all white-space changes. Sorry for that.

also, dace uses single-quote strings

**Comment by edopao** [comment]
@tbennun PR updated with (working) test.

**Comment by tbennun** [comment]
@edopao This makes the GPU tests 20 minutes (~60%) longer. I'd propose a more focused test regime.

**Review by tbennun — CHANGES_REQUESTED** [review]
see comments

**Comment by edopao** [comment]
@tbennun I agree, we should keep the duration of the CI jobs within a reasonable limit. I have updated the test.

**Pull request merged**
