### PR TITLE
Consider strides in BLAS nodes and global symbols as free symbols

### PR DESCRIPTION
**Pull request by tbennun**

### CODE REVIEW

**Comment by definelicht** [comment]
Maybe we should add an explicit test for this?

**Comment by manuelburger** [comment]
Also some bugs with regards to types. Here a float is recasted to int.
[bugTest.zip](https://github.com/spcl/dace/files/4700807/bugTest.zip)

**Comment by tbennun** [comment]
@manuelburger This bug is unrelated to the BLAS nodes in this PR, but will be addressed (with your sample as a unit test) in the next PR (the "In Progress" cards in https://github.com/spcl/dace/projects/2)

Thanks!

**Comment by tbennun** [comment]
@manuelburger updating you that this issue was fixed. Thanks!

**Pull request merged**
