### PR TITLE
Support for numpy.arange

### PR DESCRIPTION
**Pull request by alexnick83**
Adds support for numpy.arange. The 'like` keyword is currently not supported.

### CODE REVIEW

**Comment by tbennun** [comment]
@lukastruemper are you reviewing this?

**Review by lukastruemper — APPROVED** [review]
Very nice, thank you! I've never seen this "like" arg in practice, think we can merge for now

**Comment by tbennun** [comment]
@alexnick83 Why wouldn't `add_transient_like` work in this case?

**Comment by tbennun** [comment]
> @alexnick83 Why wouldn't `add_transient_like` work in this case?

@alexnick83 just read the documentation and I guess the `like` part could be used for custom descriptors as pre-padding and custom strides.

**Comment by alexnick83** [comment]
> @alexnick83 Why wouldn't `add_transient_like` work in this case?

@tbennun The `like` keyword doesn't seem to do what it does in methods such as `numpy.empty_like` (where it isn't a keyword), at least in some testing I did. The documentation is also lacking. I think a more important issue is whether we should support symbolic bounds/steps, which can be quite tricky. Theoretically, the way I wrote the replacement should support symbolic values, but we should write our own rules about how this is supposed to work and appropriate tests.

**Pull request merged**
