### PR TITLE
Transformation functions as methods

### PR DESCRIPTION
**Pull request by tbennun**
- [x] Make `can_be_applied` and others methods
- [x] Ensure Transformation classes are always initialized with properties before matching

### CODE REVIEW

**Review by definelicht — COMMENTED** [review]
Looks reasonable. Is this backwards compatible with the static methods?

Do we have a use case where we need to use properties in can_be_applied that we can test with?

**Comment by tbennun** [comment]
> Looks reasonable. Is this backwards compatible with the static methods?
> 
> Do we have a use case where we need to use properties in can_be_applied that we can test with?

@definelicht It is backwards compatible (all transformations are still using `staticmethod`s), which also answers your second question: we don't have any case where we actually use it. Any ideas?

**Comment by definelicht** [comment]
> 
> 
> > Looks reasonable. Is this backwards compatible with the static methods?
> > Do we have a use case where we need to use properties in can_be_applied that we can test with?
> 
> @definelicht It is backwards compatible (all transformations are still using `staticmethod`s), which also answers your second question: we don't have any case where we actually use it. Any ideas?

Not with existing transformations. I bumped into a need for this when looking at doing a gearboxing transformation, where the streaming memory module reads 512-bit vectors and gearboxes them into the N-bit vectors/values used by the kernel, which obviously shouldn't match if the kernel is already reading 512-bit vectors. But I'm not working on this right now :-/

**Comment by tbennun** [comment]
In any case, it definitely can't hurt to have it.

**Review by definelicht — APPROVED** [review]

**Pull request merged**
