### PR TITLE
Add code generator for Snitch

### PR DESCRIPTION
**Pull request by noah95**
This adds a new code generator back-end for the [Snitch System](https://github.com/pulp-platform/snitch). The new code generator adds:

- Emission of Snitch-compatible C-code
- Array allocation/de-allocation
- Array copy using the DMA engine
- Parallelism with OpenMP
- SSR data mover inference

Furthermore, there is a simple example in samples/snitch/axpy.py that shows how we can make use of SSR and DMA extensions.

@tbennun is familiar with the work.

### CODE REVIEW

**Comment by noah95** [comment]
The failing CI are probably due to the fact, that the new code generator is used as default, I don't know why that is.

**Comment by tbennun** [comment]
@noah95 any updates on this?

**Comment by noah95** [comment]
> @noah95 any updates on this?

Have not been working on this since I openned the PR. Perhaps @paulsc96?

**Comment by tbennun** [comment]
#1024 is merged and contains this.

**Pull request closed without merging**
