### PR TITLE
Better mangeling of the state struct in the code generator

### PR DESCRIPTION
**Pull request by philip-paul-mueller**
This PR addresses issue  #1396, by modifying the way how the name of the state struct is created.

### CODE REVIEW

**Comment by philip-paul-mueller** [comment]
According to the log `tests/python_frontend/indirections_test.py::test_indirection_scalar_range_nsdfg` failed due to a segmentation fault. However, I run it on my machine without an error. This could indicate some deeper issue. But I am not fully sure.

**Comment by phschaad** [comment]
> According to the log `tests/python_frontend/indirections_test.py::test_indirection_scalar_range_nsdfg` failed due to a segmentation fault. However, I run it on my machine without an error. This could indicate some deeper issue. But I am not fully sure.
> 
> ```python
> pytest tests/python_frontend/indirections_test.py::test_indirection_scalar_range_nsdfg
> ```

This has become a common issue in the past few days. It fails on the same test configuration every time, if it fails. For now just restarting the workflow works, but we have to look into this issue further.

**Comment by BenWeber42** [comment]
> > According to the log `tests/python_frontend/indirections_test.py::test_indirection_scalar_range_nsdfg` failed due to a segmentation fault. However, I run it on my machine without an error. This could indicate some deeper issue. But I am not fully sure.
> > ```python
> > pytest tests/python_frontend/indirections_test.py::test_indirection_scalar_range_nsdfg
> > ```
> 
> This has become a common issue in the past few days. It fails on the same test configuration every time, if it fails. For now just restarting the failing workflow works, but we have to look into this issue further.

Thanks for the context. I am tracking this here #1421. I initiated a re-run for the tests.

**Comment by philip-paul-mueller** [comment]
@BenWeber42 Interestingly  [rebooting](https://www.youtube.com/watch?v=nn2FB1P_Mn8) even works on non Windows machines.

**Comment by tbennun** [comment]
I am not sure we should make this change. Several codes depend on the existing naming convention, and the benefit is only for specific names that we should maybe disallow in validation.

**Comment by philip-paul-mueller** [comment]
Having this function has in my view multiple advantages and I do not find any disadvantages:
- There is _one single place_ where the name is composed, so if you have to change the name for whatever reason, there is one place to do that. (It will only get worse if time passes.)
- It might be a convention, but having a function indicates this directly.
- It immediately makes clear what you do.

Furthermore, while this might not be much of an argument, I learned that: "For everything you do more than once write a function" and we compose this name multiple times.

**Comment by tbennun** [comment]
> Having this function has in my view multiple advantages and I do not find any disadvantages:
> 
> * There is _one single place_ where the name is composed, so if you have to change the name for whatever reason, there is one place to do that. (It will only get worse if time passes.)
> * It might be a convention, but having a function indicates this directly.
> * It immediately makes clear what you do.
> 
> Furthermore, while this might not be much of an argument, I learned that: "For everything you do more than once write a function" and we compose this name multiple times.

I wasn't referring to the function, that part is good. I was referring to the part where we make the code less readable by changing the struct's name. One could add a dace config such as `codegen.state_struct_suffix` which is `_t` by default.

**Comment by philip-paul-mueller** [comment]
Oh, you were referring to the _generated_ C++ code. But I really like your idea with the configuration.

**Comment by philip-paul-mueller** [comment]
I have implemented your idea, but the default value of the configuration now defaults to `_state_t` instead of `_t` which.

By the way would it make sense to move the keys for the code generator to their own hierarchy?

**Comment by BenWeber42** [comment]
This seems very much like an ad-hoc solution for one instance of a much more general problem. The general problem is that Python identifiers and C++ identifiers (as generated by code-gen) are not the same. A common solution for such a problem is to have a name-mangling system. As far as I know, we currently don't have a proper name mangling system in DaCe (based on `git grep -E "mangle"`).

I think we should aim towards a general solution to the problem, because DaCe needs this anyway if we want DaCe to be robust. If we start with just an ad-hoc solution, we risk growing a name mangling system that is not suitable to solve the general problem.

I think we should take a step back and first consider a general name mangling system for DaCe. Once we have a better view of this, we can think of introducing this step by step. In particular, how should this one bug be fixed, such that the solution facilitates a path towards a more general name mangling system.

Regarding the configuration option, my big question is whether our name mangling should be configurable. We could also consider name mangling to be something internal, that shouldn't be configurable. Especially, because it's much easier to later add configuration options than to remove/change them.

**Comment by philip-paul-mueller** [comment]
@BenWeber42 
I agree, we should make the code generators more robust and for this a general name mangeling scheme should be created. But as far as I can tell this is a rather big task.

**Review by tbennun — APPROVED** [review]
LGTM

**Pull request merged**
