### PR TITLE
Consider data descriptor offset when propagating memlets

### PR DESCRIPTION
**Pull request by lukastruemper**
This PR adds the data descriptor's offsets to the memlet propagation.

### CODE REVIEW

**Comment by tbennun** [comment]
@acalotoiu I thought we were removing/deprecating offsets?

**Comment by acalotoiu** [comment]
> @acalotoiu I thought we were removing/deprecating offsets?

Yes - but while we intend to do that, actually removing them is not an engineering effort planned for the short or medium term. I propose we allow the fix for the current state for now.

**Review by acalotoiu — APPROVED** [review]
LGTM

**Comment by tbennun** [comment]
@lukastruemper do you know why this is failing and could you please fix that? Thanks!

**Pull request closed without merging**
