### PR TITLE
Speed up StateReachability pass for large state machines

### PR DESCRIPTION
**Pull request by tbennun**
The current algorithm in networkx is suboptimal. With this change, I noticed a 55x speedup in computing state reachability on realistic programs.

### CODE REVIEW

**Comment by tbennun** [comment]
@acalotoiu @mcopik tests fail because of an unrelated issue (has to do with fparser)

**Comment by mcopik** [comment]
@tbennun Indeed, it looks like an incorrect dependency version. It's really strange because it should have popped up earlier. I will look into this.

**Comment by mcopik** [comment]
@tbennun @acalotoiu It seems the module structure changed in `fparser` between `0.1.1` and `0.1.2`. In the latter, they introduced a sub-module for `Fortran2008`, which should work with this import structure. However, our requirements specify exactly the version `0.1.2` - I'm not sure why an older version would be installed.

**Comment by mcopik** [comment]
@acalotoiu @tbennun Mystery solved - they released a new version two days ago, drastically changing the package structure. While `requirements.txt` specifies an exact match on `0.1.2`, our `setup.py` has a different dependency: `fparser >= 0.1.2`.

I think it's better to move forward with the newer version - I will propose a PR to resolve this issue.

**Review by acalotoiu — APPROVED** [review]
LGTM. Thank you! It is a great performance improvement :).

**Pull request merged**
