### PR TITLE
Cherry-picked a handful of intrinsic related commits out of `multi_sdfg` branch.

### PR DESCRIPTION
**Pull request by pratyai**
These commits:
1. are chronologically early
2. fairly independent and touch a small number of files
3. thematically fit together.

This is a follow-up on the discussion about incrementally moving the stable features from `multi_sdfg` branch into `main`. All of the commits are cherry-picked to preserve the history and to have easy fast-forwarding of the `multi_sdfg` branch.

Some commits had to be slightly modified to resolve the merge conflicts during cherry-picking, but otherwise they are left as-is.

### CODE REVIEW

**Review by mcopik — APPROVED** [review]
LGTM!

**Comment by mcopik** [comment]
@pratyai One more issue: some of the test files might have commented out test function calls; it should be a leftover of prior work. Can you please verify that tests still run after enabling them again?

**Review by mcopik — CHANGES_REQUESTED** [review]
One more issue: some of the test files might have commented out test function calls; it should be a leftover of prior work. Can you please verify that tests still run after enabling them again?

**Comment by pratyai** [comment]
> One more issue: some of the test files might have commented out test function calls; it should be a leftover of prior work. Can you please verify that tests still run after enabling them again?

Done.

**Review by mcopik — APPROVED** [review]

**Pull request merged**
